#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config focused_border_color    \#0088FF
bspc config active_border_color     \#0088FF
bspc config normal_border_color     \#222
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^1'
bspc rule -a kitty desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "*:Toolkit:Picture-in-Picture" state=floating sticky=on
bspc rule -a discord desktop='^2'
bspc rule -a firefox desktop='^1'
